#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Central constants for the toolbox launcher."""

DEFAULT_APP_NAME = "ToolboxStarter"
DEFAULT_TOOLBOX_TAB_TITLE = "Toolbox"

SUPPORTED_TOOL_EXTENSIONS = ()
TOOL_FILE_FILTER = "All Files (*)"
TOOL_CONFIG_FILENAME = "tools.json"
UI_SETTINGS_FILENAME = "ui_settings.json"

ENTRY_KIND_TOOL = "tool"
ENTRY_KIND_SECTION = "section"

DEFAULT_ICON_SIZE = 72
MIN_ICON_SIZE = 40
MAX_ICON_SIZE = 160

DEFAULT_GRID_SPACING_X = 28
DEFAULT_GRID_SPACING_Y = 24
MIN_GRID_SPACING = 0
MAX_GRID_SPACING = 120

DEFAULT_SECTION_FONT_SIZE = 15
MIN_SECTION_FONT_SIZE = 10
MAX_SECTION_FONT_SIZE = 32

DEFAULT_SECTION_LINE_THICKNESS = 2
MIN_SECTION_LINE_THICKNESS = 1
MAX_SECTION_LINE_THICKNESS = 10

DEFAULT_SECTION_PROTECTED_GAP = 12
MIN_SECTION_PROTECTED_GAP = 0
MAX_SECTION_PROTECTED_GAP = 200
DEFAULT_SECTION_PROTECTED_GAP_ABOVE = DEFAULT_SECTION_PROTECTED_GAP
DEFAULT_SECTION_PROTECTED_GAP_BELOW = DEFAULT_SECTION_PROTECTED_GAP
MIN_SECTION_PROTECTED_GAP_ABOVE = MIN_SECTION_PROTECTED_GAP
MAX_SECTION_PROTECTED_GAP_ABOVE = MAX_SECTION_PROTECTED_GAP
MIN_SECTION_PROTECTED_GAP_BELOW = MIN_SECTION_PROTECTED_GAP
MAX_SECTION_PROTECTED_GAP_BELOW = MAX_SECTION_PROTECTED_GAP

DEFAULT_SECTION_LINE_COLOR = "#444a57"
DEFAULT_TILE_FRAME_COLOR = "#6f7278"
DEFAULT_TILE_HIGHLIGHT_COLOR = "#649cff"
DEFAULT_ICON_PREVIEW_BACKGROUND_COLOR = "#4a5568"
DEFAULT_TILE_BASE_FILL_ALPHA = 16
DEFAULT_TILE_HOVER_ALPHA = 26
DEFAULT_TILE_SELECTED_ALPHA = 31
DEFAULT_TILE_FRAME_ENABLED = True
DEFAULT_TILE_FRAME_THICKNESS = 1
MIN_TILE_FRAME_THICKNESS = 1
MAX_TILE_FRAME_THICKNESS = 8
DEFAULT_IMAGE_FILE_PREVIEW_ENABLED = False
IMAGE_PREVIEW_MODE_FIT = "fit"
IMAGE_PREVIEW_MODE_FILL = "fill"
DEFAULT_IMAGE_FILE_PREVIEW_MODE = IMAGE_PREVIEW_MODE_FIT
DEFAULT_VIDEO_FILE_PREVIEW_ENABLED = False
DEFAULT_HOVER_PREVIEW_ENABLED = False
HOVER_PREVIEW_SIZE = 256
VIDEO_PREVIEW_CAPTURE_SECONDS = 1.0
IMAGE_PREVIEW_EXTENSIONS = (
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".gif",
    ".webp",
    ".tif",
    ".tiff",
    ".ico",
)
VIDEO_PREVIEW_EXTENSIONS = (
    ".mp4",
    ".mkv",
    ".mov",
    ".avi",
    ".webm",
    ".wmv",
    ".m4v",
    ".flv",
    ".mpeg",
    ".mpg",
)
DEFAULT_AUTO_COMPACT_LEFT = True
LAUNCH_CLICK_MODE_SINGLE = "single"
LAUNCH_CLICK_MODE_DOUBLE = "double"
DEFAULT_LAUNCH_CLICK_MODE = LAUNCH_CLICK_MODE_DOUBLE

CANVAS_PADDING = 18
MOVE_HOLD_DELAY_MS = 300

TOP_PANEL_DEFAULT_SIZE = 170
BOTTOM_PANEL_DEFAULT_SIZE = 92

WIDGET_TABS = "tabs_main"
WIDGET_TOOLBOX_SPLITTER = "splitter_toolbox"
WIDGET_TOP_PANEL = "panel_top"
WIDGET_DROP_ZONE = "drop_zone"
WIDGET_SEARCH_INPUT = "inp_search"
WIDGET_TOOL_CANVAS = "canvas_tools"
WIDGET_BOTTOM_PANEL = "panel_bottom"
WIDGET_TOOL_DETAILS = "lbl_tool_details"

WIDGET_ICON_SIZE_SLIDER = "sld_icon_size"
WIDGET_ICON_SIZE_VALUE = "lbl_icon_size_value"
WIDGET_ICON_SIZE_LIVE_PREVIEW = "wgt_icon_size_live_preview"
WIDGET_GRID_SPACING_X_SLIDER = "sld_grid_spacing_x"
WIDGET_GRID_SPACING_X_VALUE = "lbl_grid_spacing_x_value"
WIDGET_GRID_SPACING_Y_SLIDER = "sld_grid_spacing_y"
WIDGET_GRID_SPACING_Y_VALUE = "lbl_grid_spacing_y_value"
WIDGET_AUTO_COMPACT_LEFT_CHECKBOX = "chk_auto_compact_left"
WIDGET_TAB_MANAGER_LIST = "lst_tab_manager"
BUTTON_TAB_MOVE_UP = "btn_tab_move_up"
BUTTON_TAB_MOVE_DOWN = "btn_tab_move_down"
BUTTON_APPLY_SETTINGS = "btn_apply_settings"
WIDGET_SECTION_FONT_SIZE_SLIDER = "sld_section_font_size"
WIDGET_SECTION_FONT_SIZE_VALUE = "lbl_section_font_size_value"
WIDGET_SECTION_LINE_THICKNESS_SLIDER = "sld_section_line_thickness"
WIDGET_SECTION_LINE_THICKNESS_VALUE = "lbl_section_line_thickness_value"
WIDGET_SECTION_GAP_SPINBOX = "spb_section_gap"
WIDGET_SECTION_GAP_ABOVE_SPINBOX = "spb_section_gap_above"
WIDGET_SECTION_GAP_BELOW_SPINBOX = "spb_section_gap_below"
WIDGET_SECTION_LINE_COLOR_INPUT = "inp_section_line_color"
WIDGET_SECTION_LINE_COLOR_PREVIEW = "lbl_section_line_color_preview"
WIDGET_SECTION_LINE_COLOR_BUTTON = "btn_section_line_color"
WIDGET_SECTION_SEPARATOR_LIVE_PREVIEW = "wgt_section_separator_live_preview"
WIDGET_SECTION_COLOR_LIST = "lst_section_color_manager"
WIDGET_SECTION_SELECTED_LINE_COLOR_INPUT = "inp_section_selected_line_color"
WIDGET_SECTION_SELECTED_LINE_COLOR_PREVIEW = "lbl_section_selected_line_color_preview"
WIDGET_SECTION_SELECTED_LINE_COLOR_BUTTON = "btn_section_selected_line_color"
BUTTON_SECTION_APPLY_SELECTED_LINE_COLOR = "btn_section_apply_selected_line_color"
WIDGET_SECTION_SELECTED_TITLE_COLOR_INPUT = "inp_section_selected_title_color"
WIDGET_SECTION_SELECTED_TITLE_COLOR_PREVIEW = "lbl_section_selected_title_color_preview"
WIDGET_SECTION_SELECTED_TITLE_COLOR_BUTTON = "btn_section_selected_title_color"
BUTTON_SECTION_APPLY_SELECTED_TITLE_COLOR = "btn_section_apply_selected_title_color"
WIDGET_SECTION_ALL_LINE_COLOR_INPUT = "inp_section_all_line_color"
WIDGET_SECTION_ALL_LINE_COLOR_PREVIEW = "lbl_section_all_line_color_preview"
WIDGET_SECTION_ALL_LINE_COLOR_BUTTON = "btn_section_all_line_color"
BUTTON_SECTION_APPLY_ALL_LINE_COLOR = "btn_section_apply_all_line_color"
WIDGET_SECTION_ALL_TITLE_COLOR_INPUT = "inp_section_all_title_color"
WIDGET_SECTION_ALL_TITLE_COLOR_PREVIEW = "lbl_section_all_title_color_preview"
WIDGET_SECTION_ALL_TITLE_COLOR_BUTTON = "btn_section_all_title_color"
BUTTON_SECTION_APPLY_ALL_TITLE_COLOR = "btn_section_apply_all_title_color"
BUTTON_SECTION_QUICK_ALL_LINE_DEFAULT = "btn_section_quick_all_line_default"
BUTTON_SECTION_QUICK_ALL_LINE_GRAY = "btn_section_quick_all_line_gray"
BUTTON_SECTION_QUICK_ALL_LINE_BLUE = "btn_section_quick_all_line_blue"
BUTTON_SECTION_QUICK_ALL_LINE_GREEN = "btn_section_quick_all_line_green"
BUTTON_SECTION_QUICK_ALL_LINE_RED = "btn_section_quick_all_line_red"
BUTTON_SECTION_QUICK_ALL_TITLE_DEFAULT = "btn_section_quick_all_title_default"
BUTTON_SECTION_QUICK_ALL_TITLE_WHITE = "btn_section_quick_all_title_white"
BUTTON_SECTION_QUICK_ALL_TITLE_AMBER = "btn_section_quick_all_title_amber"
BUTTON_SECTION_QUICK_ALL_TITLE_CYAN = "btn_section_quick_all_title_cyan"
BUTTON_SECTION_QUICK_ALL_TITLE_RED = "btn_section_quick_all_title_red"
WIDGET_TILE_FRAME_ENABLED_CHECKBOX = "chk_tile_frame_enabled"
WIDGET_IMAGE_FILE_PREVIEW_CHECKBOX = "chk_image_file_preview"
WIDGET_IMAGE_FILE_PREVIEW_MODE_COMBOBOX = "cmb_image_file_preview_mode"
WIDGET_VIDEO_FILE_PREVIEW_CHECKBOX = "chk_video_file_preview"
WIDGET_HOVER_PREVIEW_CHECKBOX = "chk_hover_preview"
WIDGET_TILE_FRAME_THICKNESS_SLIDER = "sld_tile_frame_thickness"
WIDGET_TILE_FRAME_THICKNESS_VALUE = "lbl_tile_frame_thickness_value"
WIDGET_TILE_FRAME_COLOR_INPUT = "inp_tile_frame_color"
WIDGET_TILE_FRAME_COLOR_PREVIEW = "lbl_tile_frame_color_preview"
WIDGET_TILE_FRAME_COLOR_BUTTON = "btn_tile_frame_color"
WIDGET_TILE_HIGHLIGHT_COLOR_INPUT = "inp_tile_highlight_color"
WIDGET_TILE_HIGHLIGHT_COLOR_PREVIEW = "lbl_tile_highlight_color_preview"
WIDGET_TILE_HIGHLIGHT_COLOR_BUTTON = "btn_tile_highlight_color"
WIDGET_ICON_PREVIEW_BACKGROUND_COLOR_INPUT = "inp_icon_preview_background_color"
WIDGET_ICON_PREVIEW_BACKGROUND_COLOR_PREVIEW = "lbl_icon_preview_background_color_preview"
WIDGET_ICON_PREVIEW_BACKGROUND_COLOR_BUTTON = "btn_icon_preview_background_color"
WIDGET_TOOL_LAUNCH_MODE_COMBOBOX = "cmb_tool_launch_mode"
# Backward-compatible aliases for older internal names.
WIDGET_TILE_FILL_COLOR_INPUT = WIDGET_TILE_HIGHLIGHT_COLOR_INPUT
WIDGET_TILE_FILL_COLOR_PREVIEW = WIDGET_TILE_HIGHLIGHT_COLOR_PREVIEW
WIDGET_TILE_FILL_COLOR_BUTTON = WIDGET_TILE_HIGHLIGHT_COLOR_BUTTON
WIDGET_EXPORT_PROFILE_BUTTON = "btn_export_profile"
WIDGET_IMPORT_PROFILE_BUTTON = "btn_import_profile"
BUTTON_CHECK_BROKEN_ENTRIES = "btn_check_broken_entries"
WIDGET_HELP_TEXT = "txt_help"
WIDGET_SETTINGS_TAB = "tab_settings"
WIDGET_HELP_TAB = "tab_help"

BUTTON_ADD_TOOL = "btn_add_tool"
BUTTON_ADD_SECTION = "btn_add_section"
BUTTON_LAUNCH_TOOL = "btn_launch_tool"
BUTTON_REMOVE_TOOL = "btn_remove_tool"
BUTTON_OPEN_CONFIG = "btn_open_config"
